# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(help_text=b'Select a label for your collection of tweets.', max_length=50),
        ),
    ]
